// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ortowlcvdbegcqqwsafe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ydG93bGN2ZGJlZ2NxcXdzYWZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTQ2NTcsImV4cCI6MjA2MzY5MDY1N30.Haj1hiiIyxHwuU01A5ktlgxp9T8Gqh3Tn6vXNNMKgrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);