
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prfowczgawhjapsdpncq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByZm93Y3pnYXdoamFwc2RwbmNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2ODM4MDYsImV4cCI6MjA2NTI1OTgwNn0.7EfQltgzdumdqdiitE_KCmzTkCoC8xewt9Qn7gIkfoc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
